apiVersion: v1
kind: Pod
metadata:
  name: my-command-pod
  namespace: my-ns
  labels:
    app: myapp-1
spec:
  containers:
  - name: myapp-container
    image: busybox
    command: ['echo']
  restartPolicy: Never
